### ISSUE TITLE
CCC requires numpy >= 1.21

### ISSUE THREAD

**Issue by jjc2718** [greenelab/ccc#28]
It might be helpful to mention this somewhere (e.g. in the documentation or `setup.py` file) - I tried to install CCC in an environment with an older numpy version and got errors with `numpy.typing.NDArray`, which seems to have been added in 1.21.

**Comment by miltondp** [comment]
@jjc2718, if you want, you can look at the [proposed fix](https://github.com/greenelab/ccc/pull/30) and test it. It works on my end following the steps there, but I wonder if it works in your old environment (in case you already have it).

**Comment by jjc2718** [comment]
I activated my old enviroment (numpy 1.19.2) and followed the steps to install from the cloned repo in your PR, and it worked for me. Thanks for looking into this!

**Comment by miltondp** [comment]
Awesome, thank you for checking, @jjc2718!
